version: "3"

services:
  service-a:
    container_name: "service-a"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NAME: "ServiceA"
      DEBUG: true
      PORT: 8081
    expose:
      - 8081
    ports:
      - "8081:8081"
    networks:
      scaffolding:

  service-b:
    container_name: "service-b"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NAME: "ServiceB"
      DEBUG: true
      PORT: 8082
    expose:
      - 8081
    ports:
      - "8082:8082"
    networks:
      scaffolding:

networks:
  scaffolding:
    driver: bridge